In [154]:
import string
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import tensorflow as tf
import pandas as pd
import nltk
# nltk.download()
from nltk import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

# Text mining 
# Text Classifications

# Bag of word
# Word embedded

# Tokenizer => StopWord, Stemmer, Puncatuation

text_economics = 'This book is intended for a two-semester course in Economics taught out of the social sciences or business school. ' \
'Principles of Economics aims to teach considerable range and depth of Economic concepts through an approachable style and methodology.' \
' The authors take a three-pronged approach to every chapter: The concept is covered with a “Heads Up” to ward off confusion, ' \
'a real-world application for that concept, and a “You Try It” section to make sure students are staying on top of the concept.'

text_sport = 'Both were chasing their own piece of history. Barcelona were trying to become the first team to claim back-to-back' \
' titles in the Champions League era while Inter were seeking a first European Cup final since 1972 and a first win in the competition since 1965.'

text_innovation = "From Alzheimer's to cancer, earwax can contain valuable indicators to a person's" \
" health. Now scientists are analysing its chemistry in the hope of finding new ways of diagnosing diseases."

# stk = sent_tokenize(text_economics)
text_economics_word_tokenize = word_tokenize(text_economics.lower())
text_sport_word_tokenize = word_tokenize(text_sport.lower())
text_innovation_word_tokenize = word_tokenize(text_innovation.lower())

documents =[text_economics,text_sport,text_innovation]
labels = ['economics','sport','innovation']

stop_words = stopwords.words('english')
puncatuations = list(string.punctuation)
stemmer = PorterStemmer()
filtred_sentences = []
for token in text_economics_word_tokenize:
    if (token not in stop_words) and (token not in puncatuations):
        word = stemmer.stem(token)
        filtred_sentences.append(word)

filtred_sentences

['book',
 'intend',
 'two-semest',
 'cours',
 'econom',
 'taught',
 'social',
 'scienc',
 'busi',
 'school',
 'principl',
 'econom',
 'aim',
 'teach',
 'consider',
 'rang',
 'depth',
 'econom',
 'concept',
 'approach',
 'style',
 'methodolog',
 'author',
 'take',
 'three-prong',
 'approach',
 'everi',
 'chapter',
 'concept',
 'cover',
 '“',
 'head',
 '”',
 'ward',
 'confus',
 'real-world',
 'applic',
 'concept',
 '“',
 'tri',
 '”',
 'section',
 'make',
 'sure',
 'student',
 'stay',
 'top',
 'concept']

In [155]:
countVec = CountVectorizer(lowercase=True)
bow = countVec.fit_transform(documents)

x = bow.toarray()
x.shape
x

array([[0, 0, 1, 0, 1, 0, 3, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 3, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0,
        0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 1, 0, 0, 4, 1,
        1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 4, 0, 1, 1, 1, 0, 4, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
        0, 3, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 3, 1, 0, 0, 0, 1, 3, 0, 0, 1, 0, 0, 0, 0, 0, 3, 1,
        1, 0, 0, 0],
       [0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        0, 0, 0, 0]], dtype=int64)

In [156]:
features = countVec.get_feature_names_out()
features

array(['1965', '1972', 'aims', 'alzheimer', 'an', 'analysing', 'and',
       'application', 'approach', 'approachable', 'are', 'authors',
       'back', 'barcelona', 'become', 'book', 'both', 'business', 'can',
       'cancer', 'champions', 'chapter', 'chasing', 'chemistry', 'claim',
       'competition', 'concept', 'concepts', 'confusion', 'considerable',
       'contain', 'course', 'covered', 'cup', 'depth', 'diagnosing',
       'diseases', 'earwax', 'economic', 'economics', 'era', 'european',
       'every', 'final', 'finding', 'first', 'for', 'from', 'heads',
       'health', 'history', 'hope', 'in', 'indicators', 'intended',
       'inter', 'is', 'it', 'its', 'league', 'make', 'methodology', 'new',
       'now', 'of', 'off', 'on', 'or', 'out', 'own', 'person', 'piece',
       'principles', 'pronged', 'range', 'real', 'school', 'sciences',
       'scientists', 'section', 'seeking', 'semester', 'since', 'social',
       'staying', 'students', 'style', 'sure', 'take', 'taught', 'teach',
       'team', 'that', 'the', 'their', 'this', 'three', 'through',
       'titles', 'to', 'top', 'try', 'trying', 'two', 'up', 'valuable',
       'ward', 'ways', 'were', 'while', 'win', 'with', 'world', 'you'],
      dtype=object)

In [157]:
df = pd.DataFrame(x,columns=features)
df

,1965,1972,aims,alzheimer,an,analysing,and,application,approach,approachable,...,up,valuable,ward,ways,were,while,win,with,world,you
0,0,0,1,0,1,0,3,1,1,1,...,1,0,1,0,0,0,0,1,1,1
1,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,3,1,1,0,0,0
2,0,0,0,1,0,1,0,0,0,0,...,0,1,0,1,0,0,0,0,0,0

In [158]:
# tf*idf

tfidf = TfidfVectorizer()
x_tdidf = tfidf.fit_transform(documents)

x_tdidf = x_tdidf.toarray()

tfidf_features = tfidf.get_feature_names_out()

df_tf_idf = pd.DataFrame(x_tdidf,columns=tfidf_features)
df_tf_idf

,1965,1972,aims,alzheimer,an,analysing,and,application,approach,approachable,...,up,valuable,ward,ways,were,while,win,with,world,you
0,0.00000,0.00000,0.101079,0.000000,0.101079,0.000000,0.230619,0.101079,0.101079,0.101079,...,0.101079,0.000000,0.101079,0.000000,0.000000,0.00000,0.00000,0.101079,0.101079,0.101079
1,0.12953,0.12953,0.000000,0.000000,0.000000,0.000000,0.098511,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.388591,0.12953,0.12953,0.000000,0.000000,0.000000
2,0.00000,0.00000,0.000000,0.199734,0.000000,0.199734,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.199734,0.000000,0.199734,0.000000,0.00000,0.00000,0.000000,0.000000,0.000000